/**
 * TODO throw these out and use LWJGL's bindings (they are way more up-to-date!)
 *
 * Based on OpenVR 1.4.18 (?)
 *
 * @author jrbudda
 *
 * Autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 */
package jopenvr;